# Generated by Django 5.2.12 on 2026-04-13 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_avataritem_useravataritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEquippedAvatarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_by', to='attractions.avataritem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_avatar_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item'), ('user', 'slot')},
            },
        ),
    ]
