# Generated by Django 5.2.12 on 2026-04-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_userequippedavataritem'),
    ]

    operations = [
    ]
