# Generated by Django 5.2.12 on 2026-04-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_backfill_equipped_defaults'),
    ]

    operations = [
    ]
