# Generated by Django 5.2.12 on 2026-04-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0005_seed_basic_avatar_items'),
    ]

    operations = [
    ]
