# Generated by Django 5.2.12 on 2026-04-20 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0007_seed_and_sync_basic_avatar_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedAttraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_by', to='attractions.attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_attractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'attraction')},
            },
        ),
    ]
