# Generated by Django 5.2.12 on 2026-04-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0009_achievement_userachievement'),
    ]

    operations = [
    ]
