name: 'Terraform Apply'

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
  ADMIN_CIDR: "0.0.0.0/0"
  CLEANUP_STALE_BACKENDS: "true"

jobs:
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run deploy script
        run: chmod +x ./deploy.sh && ./deploy.sh
